"""add building name_ko

Revision ID: 4fde05ec3582
Revises: ba023965cc7e
Create Date: 2026-09-24 22:59:44.026986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fde05ec3582'
down_revision = 'ba023965cc7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('name_ko', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'name_ko')
    # ### end Alembic commands ###
