"""initial schema

Revision ID: ba023965cc7e
Revises: 
Create Date: 2026-09-19 00:31:07.921482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba023965cc7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campus_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('building_number', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('floors', sa.Integer(), nullable=False),
    sa.Column('entrance_ids', sa.JSON(), nullable=False),
    sa.Column('facility_ids', sa.JSON(), nullable=False),
    sa.Column('accessibility', sa.JSON(), nullable=False),
    sa.Column('destination_node_id', sa.String(), nullable=True),
    sa.Column('entrance_node_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_building_number'), 'buildings', ['building_number'], unique=False)
    op.create_index(op.f('ix_buildings_campus_id'), 'buildings', ['campus_id'], unique=False)
    op.create_table('campus_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campus_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('published_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campus_versions_campus_id'), 'campus_versions', ['campus_id'], unique=False)
    op.create_table('campuses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('university_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('map_configuration', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrances_building_id'), 'entrances', ['building_id'], unique=False)
    op.create_table('facilities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_building_id'), 'facilities', ['building_id'], unique=False)
    op.create_table('route_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_node', sa.String(), nullable=False),
    sa.Column('to_node', sa.String(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('accessible', sa.Boolean(), nullable=False),
    sa.Column('indoor', sa.Boolean(), nullable=False),
    sa.Column('outdoor', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_edges_from_node'), 'route_edges', ['from_node'], unique=False)
    op.create_index(op.f('ix_route_edges_to_node'), 'route_edges', ['to_node'], unique=False)
    op.create_table('route_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_nodes')
    op.drop_index(op.f('ix_route_edges_to_node'), table_name='route_edges')
    op.drop_index(op.f('ix_route_edges_from_node'), table_name='route_edges')
    op.drop_table('route_edges')
    op.drop_index(op.f('ix_facilities_building_id'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_entrances_building_id'), table_name='entrances')
    op.drop_table('entrances')
    op.drop_table('campuses')
    op.drop_index(op.f('ix_campus_versions_campus_id'), table_name='campus_versions')
    op.drop_table('campus_versions')
    op.drop_index(op.f('ix_buildings_campus_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_building_number'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
